### ISSUE TITLE
HW09 Section 3 Plotting problem

### ISSUE THREAD

**Issue by Mr153759** [gabd-students/beardslee_jordan#9]
I'm having a problem plotting the data in section 3. Earlier it was telling me that Pollinator wasn't an object, and that my color wasn't working. For whatever reason it finally went through, but now  my plot is just one big gray box. I'm not sure where in my code it went wrong since it is all running now without giving me errors to fix.

**Comment by mtaylor-semo** [comment]
Please post your code so I can try to help. Start with the code where you open the file and include up to the part where it goes wrong.

**Comment by mtaylor-semo** [comment]
The plotting problem is because you do not have a `+` to add your `geom_point` layer to your initial `ggplot`. It stops after `ggplot`, giving you a big gray square. The plot still will not work however, because you did not use `summarize` to calculate the mean lengths and widths. As a result, you don't have `mean_length` or `mean_width` to plot. 

 I had to fix this line to get down to the plotting because `ï..Species` doesn't correspond to the `Species` column name.

```
separate(ï..Species, into = c("genus", "species")) 
```

BTW, `read_csv` is better to use than `read.csv` because it doesn't add all the extra periods in the column names, among other reasons.

**Comment by Mr153759** [comment]
Ok, thank you
